#!/usr/bin/env node

import { createHash } from "node:crypto";
import { execFileSync } from "node:child_process";
import { createRequire } from "node:module";
import { copyFileSync, mkdirSync, mkdtempSync, readFileSync, rmSync, writeFileSync } from "node:fs";
import { isIP } from "node:net";
import { dirname, join } from "node:path";
import { tmpdir } from "node:os";
import { gzipSync, gunzipSync, inflateRawSync } from "node:zlib";
import { decodeProtoMessage, isJsonNumber, parseProtoJsonMessage, parseUniqueJson, protoJsonMessageFromInternal, protoJsonMessageToValue, protoJsonText, strictUtf8, unicodeScalarCompare } from "./protojson-lossless.mjs";

const require=createRequire(import.meta.url),protobuf=require("protobufjs");require("protobufjs/ext/descriptor");
const protocRoot=process.env.OPENBINDINGS_PROTOC_36_1_ROOT||"/private/tmp/protoc-36.1";
const allowedImports=new Set(["google/protobuf/any.proto","google/protobuf/api.proto","google/protobuf/descriptor.proto","google/protobuf/duration.proto","google/protobuf/empty.proto","google/protobuf/field_mask.proto","google/protobuf/json_enumvalue_options.proto","google/protobuf/json_options.proto","google/protobuf/source_context.proto","google/protobuf/struct.proto","google/protobuf/timestamp.proto","google/protobuf/type.proto","google/protobuf/wrappers.proto"]);
const descriptorRoot=new protobuf.Root();descriptorRoot.resolvePath=(_origin,target)=>join(protocRoot,"include",target);descriptorRoot.loadSync(["google/protobuf/descriptor.proto","google/protobuf/json_enumvalue_options.proto"]);descriptorRoot.resolveAll();const descriptorSetType=descriptorRoot.lookupType("google.protobuf.FileDescriptorSet");

const fail=(message)=>{throw new Error(message)};
const canonical=(value)=>isJsonNumber(value)?value:Array.isArray(value)?value.map(canonical):value&&typeof value==="object"?Object.fromEntries(Object.keys(value).sort().map((key)=>[key,canonical(value[key])])):value;
const text=(value)=>protoJsonText(value);
const equal=(a,b)=>text(a)===text(b);
const plain=(value)=>isJsonNumber(value)?Number(value.token):Array.isArray(value)?value.map(plain):value&&typeof value==="object"?Object.fromEntries(Object.entries(value).map(([key,item])=>[key,plain(item)])):value;
function normalizeCorpusNumbers(corpus){for(const scenario of corpus.scenarios){const input=scenario.given.invocation.input,actionValues=scenario.given.invocation.actions.map((action)=>action.value);const normalized=plain(scenario);normalized.given.invocation.input=input;normalized.given.invocation.actions=normalized.given.invocation.actions.map((action,index)=>Object.hasOwn(scenario.given.invocation.actions[index],"value")?{...action,value:actionValues[index]}:action);Object.assign(scenario,normalized)}return corpus}
const emptyNative=()=>({requestHeaders:[],requestMessages:[],reflection:[],cancellations:0});
const terminal=(disposition,phase,cause,native=emptyNative(),timeline=[])=>({disposition,phase,timeline:[...timeline,{event:"terminal",disposition,cause}],native,context:{}});
const lowerCamel=(value)=>value.replace(/_([a-z])/g,(_,letter)=>letter.toUpperCase());
function canonicalBase64(value) { if(typeof value!=="string"||!/^(?:[A-Za-z0-9+/]{4})*(?:[A-Za-z0-9+/]{2}==|[A-Za-z0-9+/]{3}=)?$/.test(value)) fail("noncanonical Base64"); const bytes=Buffer.from(value,"base64"); if(bytes.toString("base64")!==value) fail("noncanonical Base64"); return bytes; }
function metadataBase64(value){if(typeof value!=="string"||!/^[A-Za-z0-9+/]*={0,2}$/.test(value)||value.length%4===1||(value.includes("=")&&value.length%4!==0))fail("noncanonical binary metadata Base64");const bytes=Buffer.from(value.padEnd(Math.ceil(value.length/4)*4,"="),"base64"),canonical=bytes.toString("base64");if(value.includes("=")?value!==canonical:value!==canonical.replace(/=+$/,""))fail("nonzero Base64 pad bits");return bytes}
function varint(bytes,offset) { let value=0n,shift=0n,index=offset; while(index<bytes.length&&index-offset<10){const byte=BigInt(bytes[index++]);if(index-offset===10&&byte>1n)fail("overflowing varint");value|=(byte&127n)<<shift;if(!(byte&128n))return[value,index];shift+=7n} fail("truncated varint"); }
function encodeVarint(value){let current=BigInt(value),out=[];while(current>127n){out.push(Number(current&127n)|128);current>>=7n}out.push(Number(current));return Buffer.from(out)}
function wireFields(bytes){const fields=new Map();let offset=0;while(offset<bytes.length){let tag;[tag,offset]=varint(bytes,offset);const number=Number(tag>>3n),wire=Number(tag&7n);let value;if(wire===0)[value,offset]=varint(bytes,offset);else if(wire===1){if(offset+8>bytes.length)fail("truncated fixed64");value=bytes.subarray(offset,offset+8);offset+=8}else if(wire===2){let length;[length,offset]=varint(bytes,offset);const end=offset+Number(length);if(end>bytes.length)fail("truncated bytes");value=bytes.subarray(offset,end);offset=end}else if(wire===5){if(offset+4>bytes.length)fail("truncated fixed32");value=bytes.subarray(offset,offset+4);offset+=4}else fail("unsupported wire type");if(!fields.has(number))fields.set(number,[]);fields.get(number).push({wire,value})}return fields}
function wireEntries(bytes){const entries=[];let offset=0;while(offset<bytes.length){let tag;[tag,offset]=varint(bytes,offset);const number=Number(tag>>3n),wire=Number(tag&7n);let value;if(wire===0)[value,offset]=varint(bytes,offset);else if(wire===1){if(offset+8>bytes.length)fail("truncated fixed64");value=bytes.subarray(offset,offset+8);offset+=8}else if(wire===2){let length;[length,offset]=varint(bytes,offset);const end=offset+Number(length);if(end>bytes.length)fail("truncated bytes");value=bytes.subarray(offset,end);offset=end}else if(wire===5){if(offset+4>bytes.length)fail("truncated fixed32");value=bytes.subarray(offset,offset+4);offset+=4}else fail("unsupported wire type");entries.push({number,wire,value})}return entries}
const strings=(fields,n)=>(fields.get(n)??[]).map(({wire,value})=>{if(wire!==2)fail("descriptor string wire");return new TextDecoder("utf-8",{fatal:true}).decode(value)});
const messages=(fields,n)=>(fields.get(n)??[]).map(({wire,value})=>{if(wire!==2)fail("descriptor message wire");return wireFields(value)});
const scalar=(fields,n,otherwise=0)=>{const entry=(fields.get(n)??[]).at(-1);if(!entry)return otherwise;if(entry.wire!==0)fail("descriptor scalar wire");return Number(entry.value)};
const typeNames={1:"double",2:"float",3:"int64",4:"uint64",5:"int32",6:"fixed64",7:"fixed32",8:"bool",9:"string",10:"group",11:"message",12:"bytes",13:"uint32",14:"enum",15:"sfixed32",16:"sfixed64",17:"sint32",18:"sint64"};
const descriptorKeys={set:new Set(["file"]),file:new Set(["name","package","dependency","publicDependency","weakDependency","messageType","enumType","service","extension","options","sourceCodeInfo","syntax","edition"]),message:new Set(["name","field","extension","nestedType","enumType","extensionRange","oneofDecl","options","reservedRange","reservedName","visibility"]),field:new Set(["name","extendee","number","label","type","typeName","defaultValue","options","oneofIndex","jsonName","proto3Optional"]),service:new Set(["name","method","options"]),method:new Set(["name","inputType","outputType","options","clientStreaming","serverStreaming"]),enum:new Set(["name","value","options","reservedRange","reservedName","visibility"]),enumValue:new Set(["name","number","options"]),oneof:new Set(["name","options"]),range:new Set(["start","end","options"]),sourceInfo:new Set(["location"]),location:new Set(["path","span","leadingComments","trailingComments","leadingDetachedComments"])};
const list=(value)=>value===undefined?[]:value;
function keys(value,kind){if(!value||typeof value!=="object"||Array.isArray(value))fail(`${kind} descriptor must be object`);for(const key of Object.keys(value))if(!descriptorKeys[kind].has(key))fail(`unknown ${kind} descriptor member ${key}`)}
function options(value,enumValue=false){if(value===undefined)return;if(!value||typeof value!=="object"||Array.isArray(value))fail("descriptor options must be object");for(const key of Object.keys(value))if(key.startsWith("[")&&!(enumValue&&key==="[pb.enumvalue.json]"))fail(`unknown descriptor option ${key}`)}
function strictDescriptorJSON(set){keys(set,"set");for(const file of list(set.file)){keys(file,"file");for(const message of list(file.messageType))strictMessage(message);for(const entry of list(file.enumType))strictEnum(entry);for(const service of list(file.service)){keys(service,"service");options(service.options);for(const method of list(service.method)){keys(method,"method");options(method.options)}}for(const field of list(file.extension))strictField(field);options(file.options);if(file.sourceCodeInfo){keys(file.sourceCodeInfo,"sourceInfo");for(const location of list(file.sourceCodeInfo.location))keys(location,"location")}}}
function strictMessage(message){keys(message,"message");for(const field of list(message.field))strictField(field);for(const field of list(message.extension))strictField(field);for(const nested of list(message.nestedType))strictMessage(nested);for(const entry of list(message.enumType))strictEnum(entry);for(const range of [...list(message.extensionRange),...list(message.reservedRange)])keys(range,"range");for(const oneof of list(message.oneofDecl)){keys(oneof,"oneof");options(oneof.options)}options(message.options)}
function strictField(field){keys(field,"field");options(field.options)}
function strictEnum(value){keys(value,"enum");for(const entry of list(value.value)){keys(entry,"enumValue");options(entry.options,true)}for(const range of list(value.reservedRange))keys(range,"range");options(value.options)}
function installEnumOption(input){const value=structuredClone(input);const visitEnums=(enums)=>{for(const entry of list(enums))for(const item of list(entry.value))if(item.options&&Object.hasOwn(item.options,"[pb.enumvalue.json]")){item.options[".pb.enumvalue.json"]=item.options["[pb.enumvalue.json]"];delete item.options["[pb.enumvalue.json]"]}};const visitMessage=(message)=>{visitEnums(message.enumType);for(const nested of list(message.nestedType))visitMessage(nested)};for(const file of list(value.file)){visitEnums(file.enumType);for(const message of list(file.messageType))visitMessage(message)}return value}
function retained(input,output,path="descriptor"){if(Array.isArray(input)){if(!Array.isArray(output)||output.length!==input.length)fail(`${path} was not preserved by strict ProtoJSON decoding`);input.forEach((entry,index)=>retained(entry,output[index],`${path}/${index}`));return}if(!input||typeof input!=="object"){if(isJsonNumber(input)){if(typeof output!=="number"||!Number.isFinite(output)||Number(input.token)!==output)fail(`${path} numeric value was coerced by descriptor ProtoJSON decoding`)}else if(input!==output)fail(`${path} value/type was coerced by descriptor ProtoJSON decoding`);return}if(!output||typeof output!=="object")fail(`${path} was not preserved by strict ProtoJSON decoding`);for(const [rawKey,value] of Object.entries(input)){const key=rawKey==="[pb.enumvalue.json]"?".pb.enumvalue.json":rawKey;if(!Object.hasOwn(output,key))fail(`unknown ProtoJSON member ${path}/${rawKey}`);retained(value,output[key],`${path}/${rawKey}`)}}
function strictDescriptorSet(value){strictDescriptorJSON(value);const installed=installEnumOption(value),message=descriptorSetType.fromObject(installed),decoded=descriptorSetType.toObject(message,{enums:String,longs:String,bytes:String,defaults:false,arrays:true,objects:true});retained(installed,decoded);return decoded}
function validateDescriptorSet(value){if(!value||!Array.isArray(value.file)||!value.file.length)fail("FileDescriptorSet.file");const names=new Set(value.file.map((file)=>file.name??""));if(names.size!==value.file.length)fail("duplicate descriptor filename");for(const file of value.file)for(const dep of file.dependency??[])if(!names.has(dep)&&!allowedImports.has(dep))fail(`missing descriptor dependency ${dep}`);return value}
function jsonFdsModel(value){
  value=validateDescriptorSet(value);
	  const services=new Map(),messagesByName=new Map(),customEnums=new Map();
	  const addEnums=(pkg,enums)=>{for(const entry of enums??[]){const fq=[pkg,entry.name].filter(Boolean).join("."),byName=new Map(),byNumber=new Map();for(const item of entry.value??[]){const custom=item.options?.[".pb.enumvalue.json"]?.string??item.options?.["[pb.enumvalue.json]"]?.string;if(custom!==undefined){byName.set(item.name,custom);byNumber.set(Number(item.number),custom)}}customEnums.set(fq,{byName,byNumber})}};
	  const addMessage=(pkg,message)=>{const fq=[pkg,message.name].filter(Boolean).join(".");messagesByName.set(fq,{name:fq,fields:(message.field??[]).map((field)=>({name:field.name,jsonName:field.jsonName??lowerCamel(field.name),number:Number(field.number),type:(field.type??"").replace(/^TYPE_/,"").toLowerCase(),typeName:(field.typeName??"").replace(/^\./,"")}))});for(const nested of message.nestedType??[])addMessage(fq,nested)};
	  for(const file of value.file){const pkg=file.package??"";addEnums(pkg,file.enumType);for(const message of file.messageType??[]){addMessage(pkg,message);const walk=(prefix,item)=>{addEnums(prefix,item.enumType);for(const nested of item.nestedType??[])walk(`${prefix}.${nested.name}`,nested)};walk(`${pkg}.${message.name}`.replace(/^\./,""),message)}for(const service of file.service??[]){const fq=[pkg,service.name].filter(Boolean).join("."),methods=new Map();for(const method of service.method??[])methods.set(method.name,{service:fq,name:method.name,input:(method.inputType??"").replace(/^\./,""),output:(method.outputType??"").replace(/^\./,""),clientStreaming:Boolean(method.clientStreaming),serverStreaming:Boolean(method.serverStreaming)});services.set(fq,methods)}}
	  const root=protobuf.Root.fromDescriptor(descriptorSetType.fromObject(value),{keepCase:true});root.resolveAll();const relaxExcludedRequired=(namespace)=>{for(const nested of namespace.nestedArray??[]){if(nested instanceof protobuf.Type)for(const field of nested.fieldsArray)if(field.required)field._features.field_presence="EXPLICIT";relaxExcludedRequired(nested)}};relaxExcludedRequired(root);
	  return{services,messages:messagesByName,root,customEnums};
}
function binaryFdsModel(bytes){
	  let descriptor;try{descriptor=descriptorSetType.decode(bytes)}catch{fail("malformed FileDescriptorSet")};const value=descriptorSetType.toObject(descriptor,{enums:String,longs:String,bytes:String,defaults:false,arrays:true,objects:true});if(!value.file?.length)fail("empty FileDescriptorSet");return jsonFdsModel(value);
}
const wireString=(entry)=>{if(!entry||entry.wire!==2)fail("reflection string wire");return new TextDecoder("utf-8",{fatal:true}).decode(entry.value)};
function reflectionRequest(bytes){const entries=wireEntries(bytes),hostEntry=entries.filter(entry=>entry.number===1).at(-1),query=entries.filter(entry=>[3,4,7].includes(entry.number)).at(-1);if(!query)return fail("reflection original_request query");return{host:hostEntry?wireString(hostEntry):"",kind:({3:"file-by-filename",4:"file-containing-symbol",7:"list-services"})[query.number],value:wireString(query)}}
function reflectionResponse(raw){const entries=wireEntries(raw),validHostEntry=entries.filter(entry=>entry.number===1).at(-1),validHost=validHostEntry===undefined?"":wireString(validHostEntry),requestEntry=entries.filter(entry=>entry.number===2).at(-1),variantEntry=entries.filter(entry=>[4,5,6,7].includes(entry.number)).at(-1);if(!requestEntry||requestEntry.wire!==2||!variantEntry||variantEntry.wire!==2)fail("reflection response required fields");const originalRequest=reflectionRequest(requestEntry.value),variant=wireFields(variantEntry.value);if(variantEntry.number===4){const protos=(variant.get(1)??[]).map(({wire,value})=>{if(wire!==2)fail("reflection descriptor wire");return Buffer.concat([Buffer.from([10]),encodeVarint(value.length),value])});return{validHost,originalRequest,responseKind:"file-descriptor-response",model:binaryFdsModel(Buffer.concat(protos))}}if(variantEntry.number===6){const serviceList=messages(variant,1).map(service=>{const names=strings(service,1);if(!names.length)return fail("reflection service name");return names.at(-1)});return{validHost,originalRequest,responseKind:"list-services-response",serviceList}}if(variantEntry.number===7){const codes=variant.get(1)??[],texts=strings(variant,2);if(codes.some((entry)=>entry.wire!==0))fail("reflection error response");return{validHost,originalRequest,responseKind:"error-response",errorResponse:{errorCode:codes.length?Number(BigInt.asIntN(32,codes.at(-1).value)):0,errorMessage:texts.at(-1)??""}}}fail("unsupported reflection response variant")}
const compiledSources=new Map();
function protoTextModel(source){if(compiledSources.has(source))return compiledSources.get(source);const temporary=mkdtempSync(join(tmpdir(),"openbindings-grpc-semantic-ts-"));try{writeFileSync(join(temporary,"source.proto"),source,{mode:0o600});for(const name of allowedImports){const destination=join(temporary,...name.split("/"));mkdirSync(dirname(destination),{recursive:true,mode:0o700});copyFileSync(join(protocRoot,"include",...name.split("/")),destination)}const output=join(temporary,"source.pb");execFileSync(join(protocRoot,"bin","protoc"),[`--proto_path=${temporary}`,"--include_imports",`--descriptor_set_out=${output}`,"source.proto"],{stdio:"pipe"});const decoded=descriptorSetType.toObject(descriptorSetType.decode(readFileSync(output)),{enums:String,longs:String,bytes:String,defaults:false,arrays:true,objects:true});const model=jsonFdsModel(validateDescriptorSet(decoded));compiledSources.set(source,model);return model}finally{rmSync(temporary,{recursive:true,force:true})}}
function descriptorModel(content){if(typeof content==="string")return protoTextModel(content);if(content&&typeof content==="object"&&Object.keys(content).length===1&&typeof content.$fileDescriptorSet==="string")return binaryFdsModel(canonicalBase64(content.$fileDescriptorSet));return jsonFdsModel(strictDescriptorSet(content))}
function messageHasSpellingCollision(type,seen=new Set()){if(seen.has(type.fullName))return false;seen.add(type.fullName);const owners=new Map();for(const field of type.fieldsArray){for(const spelling of new Set([field.name,field.options?.json_name??field.jsonName??lowerCamel(field.name)])){if(owners.has(spelling)&&owners.get(spelling)!==field.name)return true;owners.set(spelling,field.name)}}for(const field of type.fieldsArray)if(field.resolvedType instanceof protobuf.Type&&!field.resolvedType.fullName.startsWith(".google.protobuf.")&&messageHasSpellingCollision(field.resolvedType,seen))return true;return false}
function select(model,selector){const [service,methodName]=selector.split("/"),method=model.services.get(service)?.get(methodName);if(!method)fail(`selector ${selector} missing`);if(!model.messages.has(method.input)||!model.messages.has(method.output))fail(`selector ${selector} message owner missing`);const input=model.root.lookupType(method.input),output=model.root.lookupType(method.output);if(messageHasSpellingCollision(input)||messageHasSpellingCollision(output))fail(`selector ${selector} reaches excluded field-spelling collision`);return method}
function encodeMessage(model,name,value){let type;try{type=model.root.lookupType(name)}catch{fail(`missing message ${name}`)}const parsed=parseProtoJsonMessage(type,value,model.root,model.customEnums),message=protoJsonMessageFromInternal(type,parsed.internal);return Buffer.from(type.encode(message).finish())}
function requestEvidence(payload,value,compression){const compressedFlag=compression==="gzip"?1:0,encoded=compressedFlag?gzipSync(payload,{mtime:0}):payload,prefix=Buffer.alloc(5);prefix[0]=compressedFlag;prefix.writeUInt32BE(encoded.length,1);const frame=Buffer.concat([prefix,encoded]),lengthMatchesEncodedPayload=frame.readUInt32BE(1)===frame.length-5;const evidence={compressedFlag,decodedLength:payload.length,decodedPayloadBase64:payload.toString("base64"),frameBase64:frame.toString("base64"),lengthMatchesEncodedPayload,valueJson:text(value)};if(compressedFlag){if(!singleGzipMember(frame.subarray(5)).equals(payload))fail("outbound gzip roundtrip");evidence.gzipMemberValid=true}return evidence}
function decodeMessage(model,name,bytes){let type;try{type=model.root.lookupType(name)}catch{fail(`missing message ${name}`)}let message;try{message=decodeProtoMessage(type,bytes,model.root)}catch{fail("malformed Protobuf message")};return protoJsonMessageToValue(type,message,model.root,model.customEnums)}
function headerValues(groups,name){return groups.filter((group)=>group.name===name).flatMap((group)=>group.values)}
function inboundMetadata(headers,trailers=false){const owned=new Set(trailers?[":status","content-type","te","grpc-status","grpc-message","grpc-status-details-bin"]:[":status","content-type","te","grpc-encoding","grpc-accept-encoding","grpc-status","grpc-message","grpc-status-details-bin"]),groups=new Map();for(const header of headers){const name=header.name;if(name.startsWith(":")||owned.has(name))continue;if(name.startsWith("grpc-"))fail("unknown reserved response metadata");if(!groups.has(name))groups.set(name,[]);groups.get(name).push(...header.values)}return[...groups].sort(([left],[right])=>left<right?-1:left>right?1:0).map(([name,values])=>{if(name.endsWith("-bin")){const decoded=values.join(",").split(",").map((value)=>metadataBase64(value).toString("base64"));return{name,value:decoded}}if(values.some((value)=>value.length===0||!/^[\x20-\x7e]+$/.test(value)))fail("invalid ASCII response metadata");return{name,value:values.join(",")}})}
function legalResponseHeaderBlock(headers,trailers=false){let regularSeen=false;try{for(const header of headers){const name=header.name;if(typeof name!=="string"||!/^(?::[a-z]+|[0-9a-z_.-]+)$/.test(name)||!Array.isArray(header.values)||!header.values.length||header.values.some((value)=>typeof value!=="string"))return false;if(name.startsWith(":")){if(trailers||name!==":status"||regularSeen)return false}else regularSeen=true;if(trailers){if(name.startsWith("grpc-")&&!['grpc-status','grpc-message','grpc-status-details-bin'].includes(name))return false;if(['content-type','te'].includes(name))return false}else{if(name.startsWith("grpc-")&&!['grpc-encoding','grpc-accept-encoding','grpc-status','grpc-message','grpc-status-details-bin'].includes(name))return false;if(name==='te')return false}}inboundMetadata(headers,trailers);return true}catch{return false}}
function metadataHeaders(groups){return[...(groups??[])].sort((a,b)=>unicodeScalarCompare(a.name,b.name)).map((group)=>({name:group.name,values:group.name.endsWith("-bin")?[group.values.map((entry)=>{metadataBase64(entry.base64);return entry.base64}).join(",")]:group.values}))}
const reserved=(name)=>["content-type","te","user-agent"].includes(name)||name.startsWith("grpc-")||name.startsWith(":");
const metadataCollision=(groups)=>(groups??[]).some((group)=>reserved(group.name));
function admittedServerName(value){if(typeof value!=="string"||!value.length||value.endsWith(".")||value.includes("%")||value.startsWith("[")||value.endsWith("]"))return false;if(isIP(value))return true;if(value.includes(":"))return false;if(value.length>253)return false;return value.split(".").every((label)=>/^[A-Za-z0-9](?:[A-Za-z0-9-]*[A-Za-z0-9])?$/.test(label)&&label.length<=63)}
function splitAuthority(authority){if(authority.startsWith("[")){const close=authority.indexOf("]");if(close<0||authority[close+1]!==":")fail("invalid bracketed authority");return authority.slice(1,close)}const colon=authority.lastIndexOf(":");if(colon<1||authority.indexOf(":")!==colon)fail("invalid authority");return authority.slice(0,colon)}
function target(location,configured){let transport,authority;if(location.startsWith("grpc://")||location.startsWith("grpcs://")){if(configured!==undefined)fail("explicit target forbids transport override");transport=location.startsWith("grpcs://")?"tls":"plaintext";authority=location.slice(transport==="tls"?8:7);if(/[/?#@]/.test(authority))fail("invalid target authority")}else{if(configured===undefined)fail("bare target requires transport");transport=configured;authority=location}return{transport,authority,hostname:splitAuthority(authority)}}
function singleGzipMember(bytes){if(bytes.length<18||bytes[0]!==31||bytes[1]!==139||bytes[2]!==8)fail("gzip header");const flags=bytes[3];if(flags&0xe0)fail("gzip flags");let offset=10;if(flags&4){if(offset+2>bytes.length)fail("gzip extra");const length=bytes.readUInt16LE(offset);offset+=2+length}for(const bit of [8,16])if(flags&bit){while(offset<bytes.length&&bytes[offset++]!==0){}if(offset>bytes.length)fail("gzip string")}if(flags&2)offset+=2;if(offset>bytes.length-8)fail("gzip header length");const result=inflateRawSync(bytes.subarray(offset),{info:true}),end=offset+result.engine.bytesWritten+8;if(end!==bytes.length)fail("gzip must contain exactly one member with no trailing bytes");const decoded=gunzipSync(bytes);if(!decoded.equals(result.buffer))fail("gzip integrity");return decoded}
function timeoutHeader(nsText){const ns=BigInt(nsText),units=[["n",1n],["u",1000n],["m",1000000n],["S",1000000000n],["M",60000000000n],["H",3600000000000n]];for(const[suffix,size]of units){const value=(ns+size-1n)/size;if(value<=99999999n)return`${value}${suffix}`}fail("timeout unrepresentable")}
function statusDetails(raw){const result={rawBase64:raw,decoded:false};let bytes;try{bytes=metadataBase64(raw)}catch{return result}let offset=0,codePresent=false,code;try{while(offset<bytes.length){let tag;[tag,offset]=varint(bytes,offset);const field=Number(tag>>3n),wire=Number(tag&7n);if(field===1&&wire===0){let value;[value,offset]=varint(bytes,offset);codePresent=true;code=Number(BigInt.asIntN(32,value))}else if(wire===0){let ignored;[ignored,offset]=varint(bytes,offset)}else if(wire===1)offset+=8;else if(wire===2){let length;[length,offset]=varint(bytes,offset);offset+=Number(length)}else if(wire===5)offset+=4;else fail("status wire");if(offset>bytes.length)fail("status truncated")}}catch{return result}return codePresent?{rawBase64:raw,decoded:true,codePresent:true,code}:{rawBase64:raw,decoded:true,codePresent:false}}
const httpStatus=(code)=>({400:13,401:16,403:7,404:12,429:14,502:14,503:14,504:14})[code]??2;
function pointer(root,path){let value=root;for(const token of path.split("/").slice(1).map((part)=>part.replace(/~1/g,"/").replace(/~0/g,"~"))){if(value!==null&&typeof value==="object"&&Object.hasOwn(value,token))value=value[token];else return{present:false}}return{present:true,value}}
function assertionMatches(root,assertion){const found=pointer(root,assertion.path);if(assertion.absent===true)return!found.present;if(!found.present)return false;if(Object.hasOwn(assertion,"equals"))return equal(found.value,assertion.equals);const needle=assertion.contains??assertion.notContains,includes=Array.isArray(found.value)?found.value.some((entry)=>equal(entry,needle)):typeof found.value==="string"&&typeof needle==="string"?found.value.includes(needle):false;return Object.hasOwn(assertion,"contains")?includes:!includes}
function assertionFor(expected,actual,assertion){const match=assertion.path.match(/^\/native\/requestHeaders\/(\d+)(\/.*)?$/);if(!match)return assertion;const expectedHeader=expected.native.requestHeaders[Number(match[1])],index=actual.native.requestHeaders.findIndex((candidate)=>candidate.name===expectedHeader?.name);return index<0?assertion:{...assertion,path:`/native/requestHeaders/${index}${match[2]??""}`}}

function resolveReflection(scenario){
  const config=scenario.given.configuration??{},carried=target(scenario.given.source.location,config.transport),authority=carried.authority,service=scenario.given.binding.selector.split("/")[0],events=scenario.given.peer.events;
  if(metadataCollision(config.discoveryMetadata))return{failure:terminal("refusal","resolution","configuration")};
  const start=BigInt(scenario.given.runtime?.clockStartNs??"0"),deadline=config.discoveryTimeoutNs===undefined?null:start+BigInt(config.discoveryTimeoutNs);let clock=start,cursor=0;
  const reflection=[];const request=(version,stream)=>{const requestBytes=Buffer.concat([Buffer.from([10]),encodeVarint(Buffer.byteLength(authority)),Buffer.from(authority),Buffer.from([34]),encodeVarint(Buffer.byteLength(service)),Buffer.from(service)]);return{version,stream,requestKind:"file-containing-symbol",requestValue:service,host:authority,requestBase64:requestBytes.toString("base64"),openedAtNs:String(clock),deadlineNs:deadline===null?null:String(deadline),requestHeaders:[{name:":method",values:["POST"]},{name:":scheme",values:[carried.transport==="tls"?"https":"http"]},{name:":authority",values:[authority]},{name:":path",values:[`/grpc.reflection.${version}.ServerReflection/ServerReflectionInfo`]},{name:"te",values:["trailers"]},{name:"content-type",values:["application/grpc+proto"]},...metadataHeaders(config.discoveryMetadata),...(deadline===null?[]:[{name:"grpc-timeout",values:[timeoutHeader(String(deadline-clock))]}])]}};
  const consume=(version,stream)=>{reflection.push(request(version,stream));const event=events[cursor++];if(!event||!['reflection-message','reflection-status'].includes(event.type))return{kind:"transport"};if(event.reflectionVersion!==version||event.stream!==stream)fail("reflection stream correlation");clock+=BigInt(event.elapsedNs);if(deadline!==null&&clock>=deadline)return{kind:"deadline"};if(event.type==="reflection-status")return{kind:event.rpcStatus===12?"fallback":"protocol"};if(event.originalRequest?.kind!=="file-containing-symbol"||event.originalRequest?.value!==service||event.originalRequest?.host!==authority)fail("reflection message correlation");if(event.compressed)return{kind:"protocol"};const decoded=reflectionResponse(canonicalBase64(event.messageBase64));if(decoded.validHost!==event.validHost||!equal(decoded.originalRequest,event.originalRequest)||decoded.responseKind!==event.responseKind)fail("reflection raw/normalized mismatch");if(decoded.responseKind==="error-response"){if(!equal(decoded.errorResponse,event.errorResponse))fail("reflection error response mismatch");return{kind:"protocol"}}if(decoded.responseKind==="list-services-response"){if(!equal(decoded.serviceList,event.serviceList))fail("reflection service list mismatch");return{kind:"protocol"}}return{kind:"model",model:decoded.model}};
  let result=consume("v1",0);if(result.kind==="fallback")result=consume("v1alpha",1);
  const native={...emptyNative(),reflection};if(result.kind==="deadline"){native.cancellations=1;return{failure:terminal("refusal","resolution","deadline",native,[{event:"cancelled",cause:"deadline"}])}}if(result.kind!=="model")return{failure:terminal("error","resolution",result.kind,native)};return{model:result.model,native,cursor};
}

function executeScenario(scenario){
  const config=scenario.given.configuration??{};
  if(metadataCollision(config.metadata))return terminal("refusal","pre-dispatch","configuration");
  let resolved;try{if(scenario.given.source.content===undefined)resolved=resolveReflection(scenario);else resolved={model:descriptorModel(scenario.given.source.content),native:emptyNative(),cursor:0}}catch{return terminal("refusal",scenario.given.source.content===undefined?"resolution":"load","configuration")}
  if(resolved.failure)return resolved.failure;let descriptor;try{descriptor=select(resolved.model,scenario.given.binding.selector)}catch{return scenario.given.source.content===undefined?terminal("error","resolution","protocol",resolved.native):terminal("refusal","resolution","configuration",resolved.native)}
  if(descriptor.clientStreaming&&scenario.given.invocation.inputPresent)return terminal("refusal","pre-dispatch","configuration",resolved.native);
  let carried;try{carried=target(scenario.given.source.location,config.transport)}catch{return terminal("refusal","pre-dispatch","configuration",resolved.native)}
  const tls=config.tls??{},pair=[tls.clientCertificateSha256,tls.clientPrivateKeySha256].filter(Boolean).length;
  if((carried.transport==="plaintext"&&Object.keys(tls).length)||(pair===1)||(tls.serverName!==undefined&&!admittedServerName(tls.serverName)))return terminal("refusal","pre-dispatch","configuration",resolved.native);
  let timeoutValue;if(config.timeoutNs!==undefined){try{timeoutValue=timeoutHeader(config.timeoutNs)}catch{return terminal("refusal","pre-dispatch","configuration",resolved.native)}}
  const requestHeaders=[{name:":method",values:["POST"]},{name:":scheme",values:[carried.transport==="tls"?"https":"http"]},{name:":authority",values:[carried.authority]},{name:":path",values:[`/${scenario.given.binding.selector}`]},{name:"te",values:["trailers"]},{name:"content-type",values:["application/grpc+proto"]},{name:"grpc-accept-encoding",values:["gzip"]}];
  if(config.compression==="gzip")requestHeaders.push({name:"grpc-encoding",values:["gzip"]});if(timeoutValue)requestHeaders.push({name:"grpc-timeout",values:[timeoutValue]});try{requestHeaders.push(...metadataHeaders(config.metadata))}catch{return terminal("refusal","pre-dispatch","configuration",resolved.native)}
  const native={...resolved.native,requestHeaders,requestMessages:[],cancellations:0};if(scenario.given.peer.metadataMeasurement)native.metadataMeasurement=structuredClone(scenario.given.peer.metadataMeasurement);
  const peerEvents=scenario.given.peer.events.slice(resolved.cursor),timeline=[],facts=new Set(["start"]);let peerCursor=0,actionCursor=-1,inputIndex=0,outputIndex=0,halfClosed=false,cancelled=false,terminalCause,terminalDisposition,terminalPhase="completion",statusCode,wire=Buffer.alloc(0),responseEncoding="identity",elapsed=0n,pendingHttpStatus,responseDecodable=false,responseStarted=false,undecodableData=false;
  const diagnostics={grpcMessageRaw:[],statusDetails:[]};
  const connection=peerEvents[0]?.type==="connection-outcome"?peerEvents[0]:null;if(connection){peerCursor++;if(!connection.success)return terminal("error","dispatch",connection.failureCause,resolved.native);timeline.push({event:"channel-ready"});facts.add("channel-ready");const identity=tls.serverName??carried.hostname,sni=isIP(identity)?null:identity;native.channel={transport:carried.transport,dialAuthority:carried.authority,httpAuthority:carried.authority,...(carried.transport==="tls"?{tlsVersion:"1.3",alpn:"h2",sni,peerCertificateSha256:"f1fedc36f62ae3335c39f3e2de1b5719ed4c8377f3c9ee7271ecbfff76c423fd",...(tls.clientCertificateSha256?{clientCertificateSha256:tls.clientCertificateSha256}:{})}:{})}}
  let initialPayload;if(!descriptor.clientStreaming){const value=scenario.given.invocation.inputPresent?scenario.given.invocation.input:{};try{initialPayload=encodeMessage(resolved.model,descriptor.input,value)}catch{return terminal("refusal","pre-dispatch","conversion",resolved.native)}if(config.limits?.maxOutboundMessageBytes!==undefined&&initialPayload.length>config.limits.maxOutboundMessageBytes)return terminal("refusal","pre-dispatch","limit",resolved.native)}
  timeline.push({event:"rpc-opened"});facts.add("rpc-opened");
  if(scenario.given.peer.metadataMeasurement&&config.limits?.maxMetadataBytes!==undefined&&scenario.given.peer.metadataMeasurement.requestBytes>config.limits.maxMetadataBytes){timeline.push({event:"cancelled",cause:"limit"});native.requestHeaders=[];native.cancellations=1;return terminal("error","dispatch","limit",native,timeline)}
  if(!descriptor.clientStreaming){const value=scenario.given.invocation.inputPresent?scenario.given.invocation.input:{};native.requestMessages.push(requestEvidence(initialPayload,value,config.compression));timeline.push({event:"request-message",index:0},{event:"input-half-closed"});facts.add("request-half-closed");halfClosed=true}
  const ready=(after)=>after.start===true||(after.action!==undefined&&actionCursor>=after.action)||(after.native!==undefined&&facts.has(after.native));
  function commitStatus(code,phase="completion"){statusCode=code;timeline.push({event:"final-status",code});terminalCause="status";terminalDisposition=code===0?"complete":"error";terminalPhase=phase}
  function commitHeaderStatus(headers,phase){const statuses=headerValues(headers,"grpc-status"),messages=headerValues(headers,"grpc-message"),detailValues=headerValues(headers,"grpc-status-details-bin"),parsed=detailValues.map(statusDetails);diagnostics.grpcMessageRaw.push(...messages);diagnostics.statusDetails.push(...parsed);if(statuses.length!==1||!/^(?:0|[1-9][0-9]*)$/.test(statuses[0])){terminalCause="protocol";terminalDisposition="error";terminalPhase=phase;return}const rawCode=BigInt(statuses[0]),normalized=rawCode<=16n?Number(rawCode):2;commitStatus(normalized,phase);if(messages.length>1||(normalized===0&&undecodableData)||detailValues.length&&(detailValues.length!==1||!parsed[0].decoded||rawCode===0n||(parsed[0].codePresent&&BigInt(parsed[0].code)!==rawCode))){terminalCause="protocol";terminalDisposition="error"}}
  function peer(event){if(cancelled||terminalCause)fail("peer effect after terminal/cancellation");if(event.type==="response-headers"){
      if(responseStarted){terminalCause="protocol";terminalDisposition="error";terminalPhase="response";return}responseStarted=true;
      if(!legalResponseHeaderBlock(event.headers,false)){terminalCause="protocol";terminalDisposition="error";terminalPhase="response";return}
      const http=headerValues(event.headers,":status");if(http.length!==1||!/^\d{3}$/.test(http[0])){terminalCause="protocol";terminalDisposition="error";terminalPhase="response";return}
      const statuses=headerValues(event.headers,"grpc-status");if(statuses.length){native.trailingMetadata=inboundMetadata(event.headers,true);pendingHttpStatus=undefined;if(!event.endStream){terminalCause="protocol";terminalDisposition="error";terminalPhase="response"}else commitHeaderStatus(event.headers,"response");return}native.leadingMetadata=inboundMetadata(event.headers,false);
      const leadingMessages=headerValues(event.headers,"grpc-message"),leadingDetails=headerValues(event.headers,"grpc-status-details-bin");if(leadingMessages.length||leadingDetails.length){diagnostics.grpcMessageRaw.push(...leadingMessages);diagnostics.statusDetails.push(...leadingDetails.map(statusDetails));terminalCause="protocol";terminalDisposition="error";terminalPhase="response";return}
      const types=headerValues(event.headers,"content-type"),validType=types.length===1&&["application/grpc","application/grpc+proto"].includes(types[0].toLowerCase());if(http[0]!=="200"||!validType){responseDecodable=false;pendingHttpStatus=httpStatus(Number(http[0]));if(event.endStream)commitStatus(pendingHttpStatus,"response");return}responseDecodable=true;
      const encodings=headerValues(event.headers,"grpc-encoding");if(encodings.length>1||encodings.length===1&&!['identity','gzip'].includes(encodings[0])){terminalCause="protocol";terminalDisposition="error";terminalPhase="response"}else if(event.endStream){terminalCause="protocol";terminalDisposition="error";terminalPhase="response"}else responseEncoding=encodings[0]??"identity";
    }else if(event.type==="data"){
      if(!responseStarted){terminalCause="protocol";terminalDisposition="error";terminalPhase="response";return}
      const chunk=canonicalBase64(event.dataBase64);if(!responseDecodable){if(chunk.length)undecodableData=true;if(event.endStream&&pendingHttpStatus!==undefined)commitStatus(pendingHttpStatus,"response");return}wire=Buffer.concat([wire,chunk]);while(wire.length>=5&&!terminalCause){const compressed=wire[0],length=wire.readUInt32BE(1);if(compressed!==0&&compressed!==1){terminalCause="protocol";terminalDisposition="error";terminalPhase="response";wire=Buffer.alloc(0);break}if(wire.length<5+length)break;let payload=wire.subarray(5,5+length);wire=wire.subarray(5+length);if(compressed===1){if(responseEncoding!=="gzip"){terminalCause="protocol";terminalDisposition="error";terminalPhase="response";break}try{payload=singleGzipMember(payload)}catch{terminalCause="protocol";terminalDisposition="error";terminalPhase="response";break}}if(config.limits?.maxInboundMessageBytes!==undefined&&payload.length>config.limits.maxInboundMessageBytes){terminalCause="limit";terminalDisposition="error";terminalPhase="response";cancelled=true;break}try{const value=decodeMessage(resolved.model,descriptor.output,payload);timeline.push({event:"output",index:outputIndex,valueJson:text(value)});facts.add(`output-${outputIndex++}`)}catch{terminalCause="conversion";terminalDisposition="error";terminalPhase="response"}}if(event.endStream&&!terminalCause){if(wire.length){terminalCause="protocol";terminalDisposition="error";terminalPhase="response"}else if(pendingHttpStatus!==undefined)commitStatus(pendingHttpStatus,"response");else{terminalCause="protocol";terminalDisposition="error";terminalPhase="response"}}
    }else if(event.type==="trailers"){
      if(!responseStarted){terminalCause="protocol";terminalDisposition="error";terminalPhase="response";return}
      if(!legalResponseHeaderBlock(event.headers,true)){terminalCause="protocol";terminalDisposition="error";terminalPhase="completion";return}
      native.trailingMetadata=inboundMetadata(event.headers,true);
      if(headerValues(event.headers,"grpc-status").length){pendingHttpStatus=undefined;commitHeaderStatus(event.headers,"completion")}else if(pendingHttpStatus!==undefined)commitStatus(pendingHttpStatus,"completion");else{terminalCause="protocol";terminalDisposition="error";terminalPhase="completion"}
    }else if(event.type==="transport-close"){terminalCause="transport";terminalDisposition="error";terminalPhase="response"}else if(event.type==="rst-stream"){terminalCause="protocol";terminalDisposition="error";terminalPhase="response"}else if(event.type==="goaway"&&!event.currentRpcAccepted){terminalCause="transport";terminalDisposition="error";terminalPhase="response"}}
  function drain(){while(peerCursor<peerEvents.length&&!terminalCause&&ready(peerEvents[peerCursor].after)){peer(peerEvents[peerCursor++])}}
  drain();
  for(let index=0;index<scenario.given.invocation.actions.length;index++){const action=scenario.given.invocation.actions[index];actionCursor=index;if(action.type==="write"){
      if(cancelled)timeline.push({event:"input-rejected",action:index});else if(halfClosed||terminalCause)timeline.push({event:"action-failed",action:index,cause:"closed"});else{let payload;try{payload=encodeMessage(resolved.model,descriptor.input,action.value)}catch{timeline.push({event:"action-failed",action:index,cause:"conversion"},{event:"cancelled",cause:"conversion"});cancelled=true;terminalCause="conversion";terminalDisposition="error";continue}if(config.limits?.maxOutboundMessageBytes!==undefined&&payload.length>config.limits.maxOutboundMessageBytes){timeline.push({event:"action-failed",action:index,cause:"limit"},{event:"cancelled",cause:"limit"});cancelled=true;terminalCause="limit";terminalDisposition="error"}else{timeline.push({event:"input-accepted",action:index,index:inputIndex});native.requestMessages.push(requestEvidence(payload,action.value,config.compression));timeline.push({event:"request-message",index:inputIndex++})}}
    }else if(action.type==="half-close"){if(cancelled||terminalCause||halfClosed)timeline.push({event:"action-failed",action:index,cause:"closed"});else{halfClosed=true;timeline.push({event:"input-half-closed",action:index});facts.add("request-half-closed")}}
    else if(action.type==="cancel"){if(!cancelled&&!terminalCause){cancelled=true;timeline.push({event:"cancelled",action:index,cause:"caller"})}else timeline.push({event:"action-failed",action:index,cause:"closed"})}
    else if(action.type==="await-output"){if(outputIndex<=action.index)fail("await-output not satisfied")}
    else if(action.type==="await-native"){if(!facts.has(action.name))fail("await-native not satisfied")}
    else if(action.type==="advance-clock"&&config.timeoutNs){elapsed+=BigInt(action.nanoseconds);if(elapsed>=BigInt(config.timeoutNs)&&!terminalCause){cancelled=true;terminalCause="deadline";terminalDisposition="error";timeline.push({event:"cancelled",cause:"deadline"})}}
    drain()}
  drain();if(peerCursor<peerEvents.length)fail(terminalCause?"peer effect after terminal or end of stream":"unresolved peer trigger or causal cycle");if(cancelled&&!terminalCause){terminalCause="caller";terminalDisposition="error"}if(!terminalCause){terminalCause="transport";terminalDisposition="error"}if(terminalCause==="status"&&statusCode===0&&!descriptor.serverStreaming&&outputIndex!==1){terminalCause="protocol";terminalDisposition="error"}if(terminalCause==="limit"&&cancelled&&!timeline.some((event)=>event.event==="cancelled"))timeline.push({event:"cancelled",cause:"limit"});timeline.push({event:"terminal",disposition:terminalDisposition,cause:terminalCause});native.cancellations=timeline.filter((event)=>event.event==="cancelled").length;if(diagnostics.grpcMessageRaw.length)native.grpcMessageRaw=diagnostics.grpcMessageRaw;if(diagnostics.statusDetails.length)native.statusDetails=diagnostics.statusDetails;return{disposition:terminalDisposition,phase:terminalPhase,timeline,native,context:{}}
}
function objectSubset(expected,actual){if(Array.isArray(expected))return Array.isArray(actual)&&expected.length===actual.length&&expected.every((value,index)=>objectSubset(value,actual[index]));if(expected&&typeof expected==="object")return actual&&typeof actual==="object"&&!Array.isArray(actual)&&Object.entries(expected).every(([key,value])=>Object.hasOwn(actual,key)&&objectSubset(value,actual[key]));return equal(expected,actual)}
function subset(expected,actual){return expected.every((want)=>actual.some((candidate)=>objectSubset(want,candidate)))}
function orderedSubset(expected,actual){return expected.length===actual.length&&expected.every((want,index)=>objectSubset(want,actual[index]))}
function completeReflectionExpectation(want,scenario){const carried=target(scenario.given.source.location,scenario.given.configuration?.transport),headers=[{name:":method",values:["POST"]},{name:":scheme",values:[carried.transport==="tls"?"https":"http"]},{name:":authority",values:[want.host]},{name:":path",values:[`/grpc.reflection.${want.version}.ServerReflection/ServerReflectionInfo`]},{name:"te",values:["trailers"]},{name:"content-type",values:["application/grpc+proto"]},...(want.requestHeaders??[])],requestBytes=Buffer.concat([Buffer.from([10]),encodeVarint(Buffer.byteLength(want.host)),Buffer.from(want.host),Buffer.from([34]),encodeVarint(Buffer.byteLength(want.requestValue)),Buffer.from(want.requestValue)]);return{...want,requestBase64:requestBytes.toString("base64"),requestHeaders:headers}}
function reflectionExact(expected,actual,scenario){return expected.length===actual.length&&expected.every((want,index)=>equal(completeReflectionExpectation(want,scenario),actual[index]))}
function nativeTimelineBound(actual){const sends=actual.timeline.filter((event)=>event.event==="request-message");return sends.length===actual.native.requestMessages.length&&sends.every((event,index)=>event.index===index)}
function compareScenario(scenario,actual){const matched=nativeTimelineBound(actual)&&scenario.expected.some((expected)=>expected.disposition===actual.disposition&&expected.phase===actual.phase&&equal(expected.timeline,actual.timeline)&&orderedSubset(expected.native.requestMessages,actual.native.requestMessages)&&subset(expected.native.requestHeaders,actual.native.requestHeaders)&&reflectionExact(expected.native.reflection,actual.native.reflection,scenario)&&expected.native.cancellations===actual.native.cancellations&&(!expected.native.channel||equal(expected.native.channel,actual.native.channel))&&(!expected.native.grpcMessageRaw||equal(expected.native.grpcMessageRaw,actual.native.grpcMessageRaw))&&(!expected.native.statusDetails||equal(expected.native.statusDetails,actual.native.statusDetails))&&(!expected.native.metadataMeasurement||equal(expected.native.metadataMeasurement,actual.native.metadataMeasurement))&&(!expected.native.leadingMetadata||equal(expected.native.leadingMetadata,actual.native.leadingMetadata))&&(!expected.native.trailingMetadata||equal(expected.native.trailingMetadata,actual.native.trailingMetadata))&&(expected.assertions??[]).every((assertion)=>assertionMatches({native:actual.native,context:actual.context},assertionFor(expected,actual,assertion))));if(!matched)fail(`${scenario.id}: no expected alternative matched ${JSON.stringify(actual)}`);return{id:scenario.id,disposition:actual.disposition,phase:actual.phase,timeline:actual.timeline,native:actual.native}}
const corpusPath=process.argv[2];if(!corpusPath)fail("usage: node semantic.mjs <grpc.json>");const raw=readFileSync(corpusPath),corpus=normalizeCorpusNumbers(parseUniqueJson(strictUtf8(raw,"processor corpus UTF-8"))),results=[];for(const scenario of corpus.scenarios){try{results.push(compareScenario(scenario,executeScenario(scenario)))}catch(error){fail(`${scenario.id}: ${error.message}`)}}process.stdout.write(`${JSON.stringify({format:"openbindings.grpc-semantic-runner-result@1",runtime:"typescript",corpusSha256:createHash("sha256").update(raw).digest("hex"),scenarioCount:results.length,results})}\n`);
